namespace BRapp.Enums
{
    public enum TipoSistema
    {
        ORGANIZACION_GENERAL,
        METODOS_ESTILOS_DIRECCION,
        ATENCION_HOMBRE, 
        ORGANIZACION_PRODUCCION_BIENES_SERVICIOS,
        GESTION_CALIDAD,
        GESTION_CAPITAL_HUMANO,
        GESTION_AMBIENTAL,
        GESTION_INNOVACION,
        PLANIFICACION,
        CONTRATACION_ECONOMICA,
        CONTABILIDAD,
        CONTROL_INTERNO,
        RELACIONES_FINANCIERAS,
        COSTOS,
        PRECIOS,
        INFORMATIVO,
        MERCADOTECNIA,
        COMUNICACION_EMPRESARIAL,
        CAPITAL_HUMANO
    }
}
